### ISSUE TITLE
[PE-D][Tester C] remove-stat accepts stats and names that are not valid and crashes

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T11-3/tp#127]
![image.png](https://raw.githubusercontent.com/chongyongrui/ped/main/files/1b69dc4d-1c99-454b-bfd1-b95b94016f0b.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: chongyongrui/ped#14

**Comment by shawntangy** [comment]
Fixed by #173
