### ISSUE TITLE
DG Issues

### ISSUE THREAD

**Issue by hughjazzman** [AY2223S2-CS2113-T11-3/tp#83]
Nice work overall!

- [x] Do finish up the Product Scope, NFRs, Glossary, and Manual Testing sections.
![image](https://user-images.githubusercontent.com/53231968/228721341-a2f67226-a2b8-4372-b117-2f20c2ba228a.png)
- [x] (Bye) Should the activation bar end here?
![image](https://user-images.githubusercontent.com/53231968/228721420-38006019-79bd-4525-98cf-32f19a8dcc85.png)
- [x] (List, Remove) Should the activation bars begin before the operations are invoked?
![image](https://user-images.githubusercontent.com/53231968/228721581-9706fbe2-970c-4598-b6b9-d450342ee054.png)
- [x] (List) Is the control not returned from `pet` before the loop ends?
![image](https://user-images.githubusercontent.com/53231968/228721751-65e7375d-c726-41c6-b483-b5074be95c2d.png)
- [x] (Add) Consider having the error squiggly lines not be present in the diagram - not UML standard.
![image](https://user-images.githubusercontent.com/53231968/228722131-b71e55b8-8d10-43fa-afe3-24e560e7b171.png)
- [x] (Remove) Consider [using a reference frame](https://nus-cs2113-ay2223s2.github.io/website/schedule/week10/topics.html#tools-uml-sequence-diagrams-reference-frames) if the sequence diagram is too big?
- [x] (Remove) Could these return arrows be incomplete?
![image](https://user-images.githubusercontent.com/53231968/228722548-e66b578c-d0f5-44da-8b2c-02954101789d.png)

**Comment by shawntangy** [comment]
Finished up first 2 tasks with #175

**Comment by GraceZhuXY** [comment]
Finished up 3rd and 4th task with #211

**Comment by pyongjie** [comment]
Finished up 5th task with #213

**Comment by marekpinto** [comment]
Finished up 6th and 7th tasks with #192
