### ISSUE TITLE
[PE-D][Tester C] add-pet command allows a null to be input

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T11-3/tp#92]
![image.png](https://raw.githubusercontent.com/chongyongrui/ped/main/files/5043e70b-2b6e-4953-aed7-0d6fc605fcd2.png)

add-pet command allows for null to be a valid input

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: chongyongrui/ped#1

**Comment by shawntangy** [comment]
Fixed in #174
